### ISSUE TITLE
The link to JustEnoughScalaForSpark doesn’t show up after upload

### ISSUE THREAD

**Issue by HarishCherukuri** [deanwampler/JustEnoughScalaForSpark#1]
Now the line is moved towards the bottom of the page and the buttons to the right are different. Click the [JustEnoughScalaForSpark link](http://localhost:9000/notebooks/JustEnoughScalaForSpark.snb) and the tutorial notebook will open in another browser tab. (It might take a minute to load completely.)

This part is not working. I do not see the Link after upload in my spark-notebook, can you help what might be wrong.

**Comment by deanwampler** [comment]
The UI is confusing and doesn't provide good feedback. 

Check the terminal where you started Spark Notebook. Are there any errors shown that help explain the issue? I suspect the notebook failed to load for some reason. I just repeated the steps myself and they worked fine.

I just pushed an update to the [README](https://github.com/deanwampler/JustEnoughScalaForSpark) with screen shots of what you should see during the steps to load the notebook. If the terminal output isn't helpful and you don't see the same things, capture screen shots of what you see and post them here. (If GitHub's issue tracker won't let you post images, email them to me, dean at deanwampler.com). 

Other things to check (and tell me about if necessary):
* Java version? I'm using Java 8.
* Using docker or the downloaded Spark Notebook? I just tried with the downloaded Spark Notebook.
* Spark Notebook version? I'm using the version from this [download](http://spark-notebook.io/dl/zip/0.6.3/2.11/1.6.2/2.7.2/true/true) link I specify in the README.
* Windows, MacOS, Linux and version? I used MacOS El Capitan.
* Browser? I've tried Chrome and Firefox

**Comment by gbartolomebb** [comment]
Hello,

I tried unarchiving both spark-notebook-0.6.3-scala-2.11.7-spark-1.6.2-hadoop-2.7.2-with-hive-with-parquet .tgz and .zip files and both won't expand when I try to uncompress on my mac.

**Comment by deanwampler** [comment]
@HarishCherukuri if you're still having problems, try copying the `notebooks/JustEnoughScalaForSpark.snb` file to the `notebooks` directory under the Spark Notebook root directory.

@gbartolomebb, how did you attempt to expand the archives? If you used the command line, what errors do you see? Or, did you double click one of the icons? Do you have enough disk space?

You could also try going to http://spark-notebook.io and selecting your own download. Scroll down and pick one of the pre-built versions with these settings:

* Spark Notebook v0.6.3
* Scala v2.11.7
* Spark v1.6.2
* Hadoop 2.7.2
* With Hive
* With Parquet

**Comment by gbartolomebb** [comment]
It expands but only unarchives the lib folder. I do have 200gb of free storage on my Mac so I assume it's not that. Here is what I get:

tar xopf spark-notebook-0.6.3-scala-2.11.7-spark-1.6.2-hadoop-2.7.2-with-hive-with-parquet.tar
spark-notebook-0.6.3-scala-2.11.7-spark-1.6.2-hadoop-2.7.2-with-hive-with-parquet/lib/org.apache.hadoop.hadoop-common-2.7.2.jar: (Empty error message)
tar: Error exit delayed from previous errors.

**Comment by deanwampler** [comment]
@gbartolomebb it must expand the `lib` directory first, then stop when it hits a problem with that Hadoop jar file. Try [downloading the build with Hadoop 2.6.0](http://spark-notebook.io/dl/tgz/0.6.3/2.11/1.6.2/2.6.0/true/true). That version is good enough for our needs. Hopefully it will expand successfully. Let me know.

**Comment by gbartolomebb** [comment]
Was able to get it to work by just getting the package from http://spark-notebook.io.

**Comment by deanwampler** [comment]
Great. Glad that worked.

**Comment by gbartolomebb** [comment]
For some reason though the Kernel won't start when I open up any of the notebooks. I am running everything as root and getting an "Error Loading Notebook: notebook not found" when I click on JustEnoughScalaForSpark.snb.  This is what the terminal says:

[DEBUG] [09/26/2016 17:18:31.212] [New I/O worker #1] [EventStream(akka://NotebookServer)] logger log1-Slf4jLogger started
[DEBUG] [09/26/2016 17:18:31.213] [New I/O worker #1] [EventStream(akka://NotebookServer)] Default Loggers started
[INFO] Starting remoting
[INFO] Remoting started; listening on addresses :[akka.tcp://NotebookServer@127.0.0.1:53126]
[INFO] Remoting now listens on addresses: [akka.tcp://NotebookServer@127.0.0.1:53126]
[INFO] Notebooks dir is ../notebooks [at /spark-notebook/../notebooks] 
[INFO] Notebook directory is: /notebooks
[INFO] Slf4jLogger started
[INFO] View notebook 'JustEnoughScalaForSpark.snb', presentation: 'None'
[INFO] getNotebook at path JustEnoughScalaForSpark.snb
[INFO] Loading notebook at path JustEnoughScalaForSpark.snb

**Comment by deanwampler** [comment]
You must be using Docker, which apparently runs the app as root. If so, is this failing after you went through the steps to "upload a notebook", as described in the README. I would try copying the notebook again, giving it a different name. From a Mac shell prompt (i.e., not inside Docker), you can run the following:

```
$ docker ps
# Note the id printed for the docker image you're running. I'll use NNNN for it and "..." for the
# Path to where you have this git repo installed:
$ docker cp .../notebooks/JustEnoughScalaForSpark.snb NNNN:/opt/docker/notebooks/JustEnoughScalaForSpark2.snb
# Confirm it's there:
$ docker exec -it NNNN ls -l /opt/docker/notebooks
```
You should also see it appear soon in the Spark Notebook home page. Try clicking that one.

I just went through these steps myself. 

One last thing. Is it possible you're running out of memory? If you have several notebooks running, click the "Running" tab on the Spark Notebook home page and kill any other ones.

**Comment by gbartolomebb** [comment]
Actually running it local, the odd part is I can't run any of the Notebooks the Kernel only starts when I create a new Notebook but it doesn't default to the Notebooks already created. My ram is good so I don't think it's that.

Thx!

**Comment by deanwampler** [comment]
Oh, if you're not using docker, then run Spark Notebook as yourself. It's just a JVM app. Sounds like a Spark Notebook bug.
