### ISSUE TITLE
opening notebook in jupyter / toree

### ISSUE THREAD

**Issue by sublimotion** [deanwampler/JustEnoughScalaForSpark#5]
I tried to open the .snb file in jupyter but jupyter doesn't seem to recognize as a valid notebook.

After renaming the file from .snb to .ipynb i am getting a validation error.

Notebook Validation failed: 'nbformat_minor' is a required property:

**Comment by deanwampler** [comment]
Jupyter is not supported. You have to use [Spark Notebook](http://spark-notebook.io), as described in the README. However, if you checkout the `oriole` branch (`git checkout oriole`), you'll see a similar version of the notebook in `oriole/notebooks/*.ipynb` designed for Jupyter + Toree.

**Comment by deanwampler** [comment]
Closing this, as the project now uses Jupyter!
